import React from 'react';
import AppModals from './AppModals';

export default function AppModalsContainer({
  showReminderModal,
  setShowReminderModal,
  reminderTime,
  setReminderTime,
  reminderModes,
  setReminderModes,
  handleSetReminder,
  setReminderNoteId,
  activeShareNoteId,
  setActiveShareNoteId,
  friends,
  selectedFriendCodes,
  setSelectedFriendCodes,
  handleSendShareInvitation,
  handleAcceptShare,
  handleRejectShare,
  lightboxUrl,
  setLightboxUrl,
  handleCloseLightbox,
  lightboxOverlayRef,
  lightboxImgRef,
  handleLightboxDoubleTap,
  previewFileModal,
  setPreviewFileModal,
  showShareModal,
  setShowShareModal,
  editingNote,
  handleShareNoteImage,
  confirmDialog,
  setConfirmDialog,
  showAvatarPicker,
  setShowAvatarPicker,
  user,
  setToast,
  handleSelectAvatar,
  DEFAULT_AVATARS,
  checkAndRequestNotificationPermission,
  pendingWidgetAlarmCtx,
  handleCancelWidgetAlarm,
  quickReminderTitle,
  setQuickReminderTitle,
  quickReminderTime,
  setQuickReminderTime,
  quickReminderModes,
  setQuickReminderModes,
  handleCreateWidgetAlarm,
  notes,
  showFeedbackModal,
  setShowFeedbackModal,
  myCode,
  profileName,
  theme,
  lang,
  t,
  triggerHaptic
}) {
  return (
    <AppModals
      notes={notes}
      showReminderModal={showReminderModal}
      setShowReminderModal={setShowReminderModal}
      reminderTime={reminderTime}
      setReminderTime={setReminderTime}
      reminderModes={reminderModes}
      setReminderModes={setReminderModes}
      handleSetReminder={handleSetReminder}
      setReminderNoteId={setReminderNoteId}
      activeShareNoteId={activeShareNoteId}
      setActiveShareNoteId={setActiveShareNoteId}
      friends={friends}
      selectedFriendCodes={selectedFriendCodes}
      setSelectedFriendCodes={setSelectedFriendCodes}
      handleSendShareInvitation={handleSendShareInvitation}
      handleAcceptShare={handleAcceptShare}
      handleRejectShare={handleRejectShare}
      lightboxUrl={lightboxUrl}
      setLightboxUrl={setLightboxUrl}
      handleCloseLightbox={handleCloseLightbox}
      lightboxOverlayRef={lightboxOverlayRef}
      lightboxImgRef={lightboxImgRef}
      handleLightboxDoubleTap={handleLightboxDoubleTap}
      previewFileModal={previewFileModal}
      setPreviewFileModal={setPreviewFileModal}
      showShareModal={showShareModal}
      setShowShareModal={setShowShareModal}
      editingNote={editingNote}
      handleShareNoteImage={handleShareNoteImage}
      confirmDialog={confirmDialog}
      setConfirmDialog={setConfirmDialog}
      showAvatarPicker={showAvatarPicker}
      setShowAvatarPicker={setShowAvatarPicker}
      user={user}
      setToast={setToast}
      handleSelectAvatar={handleSelectAvatar}
      DEFAULT_AVATARS={DEFAULT_AVATARS}
      checkAndRequestNotificationPermission={checkAndRequestNotificationPermission}
      pendingWidgetAlarmCtx={pendingWidgetAlarmCtx}
      handleCancelWidgetAlarm={handleCancelWidgetAlarm}
      quickReminderTitle={quickReminderTitle}
      setQuickReminderTitle={setQuickReminderTitle}
      quickReminderTime={quickReminderTime}
      setQuickReminderTime={setQuickReminderTime}
      quickReminderModes={quickReminderModes}
      setQuickReminderModes={setQuickReminderModes}
      handleCreateWidgetAlarm={handleCreateWidgetAlarm}
      showFeedbackModal={showFeedbackModal}
      setShowFeedbackModal={setShowFeedbackModal}
      myCode={myCode}
      profileName={profileName}
      theme={theme}
      lang={lang}
      t={t}
      triggerHaptic={triggerHaptic}
    />
  );
}
