export const paywallStyles = {
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.85)",
    backdropFilter: "blur(8px)",
    zIndex: 9000,
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "center",
    overflowY: "auto",
    padding: "0",
  },
  container: {
    width: "100%",
    maxWidth: "480px",
    minHeight: "100dvh",
    background: "#09090f",
    display: "flex",
    flexDirection: "column",
    padding: "0 0 40px 0",
    position: "relative",
  },
  closeBtn: {
    position: "absolute",
    top: "16px",
    right: "16px",
    background: "rgba(255,255,255,0.08)",
    border: "1px solid rgba(255,255,255,0.12)",
    color: "#9CA3AF",
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    fontSize: "14px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },
  header: {
    padding: "48px 20px 24px",
    textAlign: "center",
    background: "linear-gradient(180deg, #0d0d1a 0%, #09090f 100%)",
  },
  logoRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    marginBottom: "20px",
  },
  logoText: {
    fontSize: "20px",
    fontWeight: "700",
    color: "white",
    letterSpacing: "-0.5px",
  },
  title: {
    fontSize: "26px",
    fontWeight: "800",
    color: "white",
    margin: "0 0 8px 0",
    letterSpacing: "-0.5px",
  },
  subtitle: {
    fontSize: "14px",
    color: "#9CA3AF",
    margin: "0 0 20px 0",
    lineHeight: 1.5,
  },
  billingToggle: {
    display: "inline-flex",
    background: "rgba(255,255,255,0.06)",
    borderRadius: "12px",
    padding: "4px",
    gap: "4px",
  },
  toggleBtn: {
    background: "none",
    border: "none",
    color: "#6B7280",
    fontSize: "13px",
    fontWeight: "600",
    padding: "8px 16px",
    borderRadius: "99px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "6px",
    transition: "all 0.2s",
  },
  saveBadge: {
    background: "linear-gradient(135deg, #16a34a, #22c55e)",
    color: "white",
    fontSize: "10px",
    fontWeight: "700",
    padding: "2px 6px",
    borderRadius: "99px",
  },
  plansContainer: {
    padding: "8px 16px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
};
