import React from 'react';
import AppModals from './AppModals';

export default function AppModalsContainer({
  showReminderModal,
  setShowReminderModal,
  reminderTime,
  setReminderTime,
  reminderModes,
  setReminderModes,
  handleSetReminder,
  setReminderNoteId,
  activeShareNoteId,
  setActiveShareNoteId,
  friends,
  selectedFriendCodes,
  setSelectedFriendCodes,
  handleSendShareInvitation,
  handleAcceptShare,
  handleRejectShare,
  lightboxUrl,
  setLightboxUrl,
  handleCloseLightbox,
  lightboxOverlayRef,
  lightboxImgRef,
  handleLightboxDoubleTap,
  previewFileModal,
  setPreviewFileModal,
  showShareModal,
  setShowShareModal,
  editingNote,
  handleShareNoteImage,
  showPaywall,
  setShowPaywall,
  userPlan,
  setUserPlan,
  planNotification,
  setPlanNotification,
  confirmDialog,
  setConfirmDialog,
  getLostFeatures,
  getChangedFeatures,
  PLAN_LEVELS,
  showAdModal,
  setShowAdModal,
  showAvatarPicker,
  setShowAvatarPicker,
  user,
  setToast,
  cropperImage,
  setCropperImage,
  handleSelectAvatar,
  DEFAULT_AVATARS,
  checkAndRequestPermission,
  checkAndRequestNotificationPermission,
  pendingWidgetAlarmCtx,
  handleCancelWidgetAlarm,
  quickReminderTitle,
  setQuickReminderTitle,
  quickReminderTime,
  setQuickReminderTime,
  quickReminderModes,
  setQuickReminderModes,
  handleCreateWidgetAlarm,
  showRewardedAdModal,
  setShowRewardedAdModal,
  pendingShareReward,
  setPendingShareReward,
  handleRewardedShareCallback,
  notes,
  showFeedbackModal,
  setShowFeedbackModal,
  nudgeTargetNote,
  setNudgeTargetNote,
  handleSendNudge,
  myCode,
  profileName,
  theme,
  lang,
  t,
  triggerHaptic
}) {
  return (
    <AppModals
      notes={notes}
      showReminderModal={showReminderModal}
      setShowReminderModal={setShowReminderModal}
      reminderTime={reminderTime}
      setReminderTime={setReminderTime}
      reminderModes={reminderModes}
      setReminderModes={setReminderModes}
      handleSetReminder={handleSetReminder}
      setReminderNoteId={setReminderNoteId}
      activeShareNoteId={activeShareNoteId}
      setActiveShareNoteId={setActiveShareNoteId}
      friends={friends}
      selectedFriendCodes={selectedFriendCodes}
      setSelectedFriendCodes={setSelectedFriendCodes}
      handleSendShareInvitation={handleSendShareInvitation}
      handleAcceptShare={handleAcceptShare}
      handleRejectShare={handleRejectShare}
      lightboxUrl={lightboxUrl}
      setLightboxUrl={setLightboxUrl}
      handleCloseLightbox={handleCloseLightbox}
      lightboxOverlayRef={lightboxOverlayRef}
      lightboxImgRef={lightboxImgRef}
      handleLightboxDoubleTap={handleLightboxDoubleTap}
      previewFileModal={previewFileModal}
      setPreviewFileModal={setPreviewFileModal}
      showShareModal={showShareModal}
      setShowShareModal={setShowShareModal}
      editingNote={editingNote}
      handleShareNoteImage={handleShareNoteImage}
      showPaywall={showPaywall}
      setShowPaywall={setShowPaywall}
      userPlan={userPlan}
      setUserPlan={setUserPlan}
      planNotification={planNotification}
      setPlanNotification={setPlanNotification}
      confirmDialog={confirmDialog}
      setConfirmDialog={setConfirmDialog}
      getLostFeatures={getLostFeatures}
      getChangedFeatures={getChangedFeatures}
      PLAN_LEVELS={PLAN_LEVELS}
      showAdModal={showAdModal}
      setShowAdModal={setShowAdModal}
      showAvatarPicker={showAvatarPicker}
      setShowAvatarPicker={setShowAvatarPicker}
      user={user}
      setToast={setToast}
      cropperImage={cropperImage}
      setCropperImage={setCropperImage}
      handleSelectAvatar={handleSelectAvatar}
      DEFAULT_AVATARS={DEFAULT_AVATARS}
      checkAndRequestPermission={checkAndRequestPermission}
      checkAndRequestNotificationPermission={checkAndRequestNotificationPermission}
      pendingWidgetAlarmCtx={pendingWidgetAlarmCtx}
      handleCancelWidgetAlarm={handleCancelWidgetAlarm}
      quickReminderTitle={quickReminderTitle}
      setQuickReminderTitle={setQuickReminderTitle}
      quickReminderTime={quickReminderTime}
      setQuickReminderTime={setQuickReminderTime}
      quickReminderModes={quickReminderModes}
      setQuickReminderModes={setQuickReminderModes}
      handleCreateWidgetAlarm={handleCreateWidgetAlarm}
      showRewardedAdModal={showRewardedAdModal}
      setShowRewardedAdModal={setShowRewardedAdModal}
      pendingShareReward={pendingShareReward}
      setPendingShareReward={setPendingShareReward}
      handleRewardedShareCallback={handleRewardedShareCallback}
      showFeedbackModal={showFeedbackModal}
      setShowFeedbackModal={setShowFeedbackModal}
      nudgeTargetNote={nudgeTargetNote}
      setNudgeTargetNote={setNudgeTargetNote}
      handleSendNudge={handleSendNudge}
      myCode={myCode}
      profileName={profileName}
      theme={theme}
      lang={lang}
      t={t}
      triggerHaptic={triggerHaptic}
    />
  );
}
