import React from 'react';
import HeaderBar from '@layout/HeaderBar';
import WorkspaceTabs from '@layout/WorkspaceTabs';
import BottomNavBar from '@layout/BottomNavBar';
import NoteEditor from '@features/notes/components/NoteEditor';
import { ensureElementVisible as ensureElementVisibleUtil } from '@shared/utils/editorKeyboardUtils';

export default function AppWorkspaceContainer({
  editingNote,
  setEditingNote,
  friends,
  reminders,
  theme,
  lang,
  t,
  showEditorMenu,
  setShowEditorMenu,
  activeFormatBlockId,
  setActiveFormatBlockId,
  showFormatToolbar,
  setShowFormatToolbar,
  blockFormStates,
  setBlockFormStates,
  activeTodoItemId,
  setActiveTodoItemId,
  activeAudioPlayingId,
  setActiveAudioPlayingId,
  activeAudioProgress,
  setLightboxUrl,
  fileInputRef,
  focusedBlockRef,
  currentAudioRef,
  permissionStates,
  editorUndoStack,
  editorRedoStack,
  isRecording,
  recordingSeconds,
  setToast,
  getRemainingTimeText,
  setReminderTime,
  setReminderNoteId,
  setShowReminderModal,
  setQuickReminderTitle,
  setQuickReminderTime,
  setPendingWidgetAlarmCtx,
  setShowShareModal,
  userPlan,
  notes,
  triggerHaptic,
  checkAndRequestNotificationPermission,
  checkAndRequestPermission,
  showPermissionDialog,
  requestBiometricAuth,
  persistNotes,
  setNotes,
  openEditingNote,
  handleCloseEditor,
  handleFileChange,
  handleUndo,
  handleRedo,
  handleRestoreNote,
  handlePermanentDelete,
  handleMoveToTrash,
  handleUpdateNote,
  handleUpdateBlock,
  handleDeleteBlock,
  handleTextareaKeyDown,
  handleOpenFile,
  handlePlayPauseAudio,
  handleAddDebtItem,
  handleDeleteDebtItem,
  handleAddExpenseItem,
  handleDeleteExpenseItem,
  handleExpenseTitleChange,
  handleTodoTitleChange,
  handleToggleTodoItem,
  handleDeleteTodoItem,
  handleAddTodoItem,
  handleSetupSplit,
  handleAddSplitExpense,
  handleDeleteSplitExpense,
  handleDeleteExamBlock,
  handleDeleteBillBlock,
  handlePayBill,
  handleDeleteBillPaymentItem,
  handleInsertWidget,
  handleSendNudge,
  startRecording,
  cancelRecording,
  stopRecording,
  ensureElementVisible = ensureElementVisibleUtil,
  setConfirmDialog,
  activeTab,
  setActiveTab,
  getVisibleNotes,
  activeMenuNoteId,
  setActiveMenuNoteId,
  setActiveShareNoteId,
  setNudgeTargetNote,
  setSelectedFriendCodes,
  pendingShareRequests,
  handleAcceptShare,
  handleRejectShare,
  handleLeaveShare,
  handleRequestMicPermission,
  handleRequestStoragePermission,
  handleRequestAudioPermission,
  handleRequestLocationPermission,
  handleCancelReminder,
  handleBulkRestoreNotes,
  handleBulkPermanentDelete,
  setTheme,
  setLang,
  profileSubTab,
  setProfileSubTab,
  user,
  setShowAvatarPicker,
  profileName,
  handleUpdateProfileName,
  getStorageUsageBytes,
  formatBytes,
  setShowFeedbackModal,
  myCode,
  partnerCodeInput,
  setPartnerCodeInput,
  formatFriendCode,
  isSendingRequest,
  handleSendFriendRequest,
  friendRequests,
  handleAcceptFriendRequest,
  handleRejectFriendRequest,
  handleCancelFriendRequest,
  handleDisconnect,
  handleLogout,
  DEFAULT_AVATARS,
  handleTabClick,
  handleCreateNote
}) {
  if (editingNote) {
    return (
      <NoteEditor
        editingNote={editingNote}
        setEditingNote={setEditingNote}
        friends={friends}
        reminders={reminders}
        theme={theme}
        lang={lang}
        t={t}
        showEditorMenu={showEditorMenu}
        setShowEditorMenu={setShowEditorMenu}
        activeFormatBlockId={activeFormatBlockId}
        setActiveFormatBlockId={setActiveFormatBlockId}
        showFormatToolbar={showFormatToolbar}
        setShowFormatToolbar={setShowFormatToolbar}
        blockFormStates={blockFormStates}
        setBlockFormStates={setBlockFormStates}
        activeTodoItemId={activeTodoItemId}
        setActiveTodoItemId={setActiveTodoItemId}
        activeAudioPlayingId={activeAudioPlayingId}
        setActiveAudioPlayingId={setActiveAudioPlayingId}
        activeAudioProgress={activeAudioProgress}
        setLightboxUrl={setLightboxUrl}
        fileInputRef={fileInputRef}
        focusedBlockRef={focusedBlockRef}
        currentAudioRef={currentAudioRef}
        permissionStates={permissionStates}
        editorUndoStack={editorUndoStack}
        editorRedoStack={editorRedoStack}
        isRecording={isRecording}
        recordingSeconds={recordingSeconds}
        setToast={setToast}
        getRemainingTimeText={getRemainingTimeText}
        setReminderTime={setReminderTime}
        setReminderNoteId={setReminderNoteId}
        setShowReminderModal={setShowReminderModal}
        setQuickReminderTitle={setQuickReminderTitle}
        setQuickReminderTime={setQuickReminderTime}
        setPendingWidgetAlarmCtx={setPendingWidgetAlarmCtx}
        setShowShareModal={setShowShareModal}
        userPlan={userPlan}
        notes={notes}
        triggerHaptic={triggerHaptic}
        checkAndRequestNotificationPermission={checkAndRequestNotificationPermission}
        checkAndRequestPermission={checkAndRequestPermission}
        showPermissionDialog={showPermissionDialog}
        requestBiometricAuth={requestBiometricAuth}
        persistNotes={persistNotes}
        setNotes={setNotes}
        handleCloseEditor={handleCloseEditor}
        handleFileChange={handleFileChange}
        handleUndo={handleUndo}
        handleRedo={handleRedo}
        handleRestoreNote={handleRestoreNote}
        handlePermanentDelete={handlePermanentDelete}
        handleMoveToTrash={handleMoveToTrash}
        handleUpdateNote={handleUpdateNote}
        handleUpdateBlock={handleUpdateBlock}
        handleDeleteBlock={handleDeleteBlock}
        handleTextareaKeyDown={handleTextareaKeyDown}
        handleOpenFile={handleOpenFile}
        handlePlayPauseAudio={handlePlayPauseAudio}
        handleAddDebtItem={handleAddDebtItem}
        handleDeleteDebtItem={handleDeleteDebtItem}
        handleAddExpenseItem={handleAddExpenseItem}
        handleDeleteExpenseItem={handleDeleteExpenseItem}
        handleExpenseTitleChange={handleExpenseTitleChange}
        handleTodoTitleChange={handleTodoTitleChange}
        handleToggleTodoItem={handleToggleTodoItem}
        handleDeleteTodoItem={handleDeleteTodoItem}
        handleAddTodoItem={handleAddTodoItem}
        handleSetupSplit={handleSetupSplit}
        handleAddSplitExpense={handleAddSplitExpense}
        handleDeleteSplitExpense={handleDeleteSplitExpense}
        handleDeleteExamBlock={handleDeleteExamBlock}
        handleDeleteBillBlock={handleDeleteBillBlock}
        handlePayBill={handlePayBill}
        handleDeleteBillPaymentItem={handleDeleteBillPaymentItem}
        handleInsertWidget={handleInsertWidget}
        handleSendNudge={handleSendNudge}
        startRecording={startRecording}
        cancelRecording={cancelRecording}
        stopRecording={stopRecording}
        reminders={reminders}
        handleCancelReminder={handleCancelReminder}
        ensureElementVisible={ensureElementVisible}
        setConfirmDialog={setConfirmDialog}
      />
    );
  }

  return (
    <>
      {activeTab !== 'trash' && (
        <HeaderBar
          setShowFeedbackModal={setShowFeedbackModal}
          triggerHaptic={triggerHaptic}
          lang={lang}
          t={t}
          theme={theme}
        />
      )}

      <WorkspaceTabs
        activeTab={activeTab}
        getVisibleNotes={getVisibleNotes}
        notes={notes}
        handleLeaveShare={handleLeaveShare}
        reminders={reminders}
        activeMenuNoteId={activeMenuNoteId}
        setActiveMenuNoteId={setActiveMenuNoteId}
        requestBiometricAuth={requestBiometricAuth}
        setNotes={setNotes}
        persistNotes={persistNotes}
        setToast={setToast}
        handleMoveToTrash={handleMoveToTrash}
        openEditingNote={openEditingNote}
        setActiveTab={setActiveTab}
        setSelectedFriendCodes={setSelectedFriendCodes}
        checkAndRequestNotificationPermission={checkAndRequestNotificationPermission}
        handleRequestMicPermission={handleRequestMicPermission}
        handleRequestStoragePermission={handleRequestStoragePermission}
        handleRequestAudioPermission={handleRequestAudioPermission}
        handleRequestLocationPermission={handleRequestLocationPermission}
        setReminderNoteId={setReminderNoteId}
        setShowReminderModal={setShowReminderModal}
        setActiveShareNoteId={setActiveShareNoteId}
        setNudgeTargetNote={setNudgeTargetNote}
        pendingShareRequests={pendingShareRequests}
        handleAcceptShare={handleAcceptShare}
        handleRejectShare={handleRejectShare}
        permissionStates={permissionStates}
        handleCancelReminder={handleCancelReminder}
        handleRestoreNote={handleRestoreNote}
        handlePermanentDelete={handlePermanentDelete}
        handleBulkRestoreNotes={handleBulkRestoreNotes}
        handleBulkPermanentDelete={handleBulkPermanentDelete}
        userPlan={userPlan}
        theme={theme}
        setTheme={setTheme}
        lang={lang}
        setLang={setLang}
        triggerHaptic={triggerHaptic}
        profileSubTab={profileSubTab}
        setProfileSubTab={setProfileSubTab}
        user={user}
        setShowAvatarPicker={setShowAvatarPicker}
        profileName={profileName}
        handleUpdateProfileName={handleUpdateProfileName}
        getStorageUsageBytes={getStorageUsageBytes}
        formatBytes={formatBytes}
        myCode={myCode}
        partnerCodeInput={partnerCodeInput}
        setPartnerCodeInput={setPartnerCodeInput}
        formatFriendCode={formatFriendCode}
        isSendingRequest={isSendingRequest}
        handleSendFriendRequest={handleSendFriendRequest}
        friendRequests={friendRequests}
        handleAcceptFriendRequest={handleAcceptFriendRequest}
        handleRejectFriendRequest={handleRejectFriendRequest}
        handleCancelFriendRequest={handleCancelFriendRequest}
        friends={friends}
        handleDisconnect={handleDisconnect}
        handleLogout={handleLogout}
        DEFAULT_AVATARS={DEFAULT_AVATARS}
        t={t}
      />

      <BottomNavBar
        activeTab={activeTab}
        handleTabClick={handleTabClick}
        handleCreateNote={handleCreateNote}
        pendingShareCount={Array.isArray(pendingShareRequests) ? pendingShareRequests.length : 0}
        t={t}
      />
    </>
  );
}
